// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UPWeJqykbPNYc1xZBZ-QhjvqRfnok1w',
    appId: '1:738605889095:android:72875be6583e20c8892362',
    messagingSenderId: '738605889095',
    projectId: 'dosify-v2',
    storageBucket: 'dosify-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4msN_45xA5whs0B_frYhmTZDZlVYqG7I',
    appId: '1:738605889095:ios:a24e13716503619b892362',
    messagingSenderId: '738605889095',
    projectId: 'dosify-v2',
    storageBucket: 'dosify-v2.firebasestorage.app',
    iosClientId: '738605889095-3ass2sleq3pddqsnp1s1gap6gl27q7ls.apps.googleusercontent.com',
    iosBundleId: 'com.kinemspa.dosifyV2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz4Cta_7NY1Dgmoyma_yjg81Mmxx1xluM',
    appId: '1:738605889095:web:5897bd78cff3796b892362',
    messagingSenderId: '738605889095',
    projectId: 'dosify-v2',
    authDomain: 'dosify-v2.firebaseapp.com',
    storageBucket: 'dosify-v2.firebasestorage.app',
    measurementId: 'G-KDRXX1Z9JZ',
  );

}