import 'package:hive/hive.dart';

part 'medication.g.dart'; // Generated by build_runner

@HiveType(typeId: 0)
class Medication {
  @HiveField(0)
  int? id;

  @HiveField(1)
  String name;

  @HiveField(2)
  MedicationType type;

  @HiveField(3)
  double strength;

  @HiveField(4)
  String unit;

  @HiveField(5)
  int stock;

  @HiveField(6)
  int lowStockThreshold;

  @HiveField(7)
  bool? reconstitution;

  Medication({
    this.id,
    required this.name,
    required this.type,
    required this.strength,
    required this.unit,
    required this.stock,
    required this.lowStockThreshold,
    this.reconstitution,
  });
}

enum MedicationType {
  tablet,
  injection,
  drops,
  other,
}